export const INDUSTRIES = [
  "2/3 Wheelers", "Abrasives & Bearings", "Advertising & Media Agencies", "Aerospace & Defense", "Airline", 
  "Airport & Airport services", "Aluminium", "Aluminium, Copper & Zinc Products", "Amusement Parks/ Other Recreation", 
  "Animal Feed", "Asset Management Company", "Auto Components & Equipments", "Auto Dealer", "Biotechnology", 
  "Breweries & Distilleries", "Business Process Outsourcing (BPO)", "Cables - Electricals", "Carbon Black", 
  "Castings & Forgings", "Cement & Cement Products", "Ceramics", "Cigarettes & Tobacco Products", 
  "Civil Construction", "Coal", "Commercial Vehicles", "Commodity Chemicals", "Compressors, Pumps & Diesel Engines", 
  "Computers - Software & Consulting", "Computers Hardware & Equipments", "Construction Vehicles", 
  "Consulting Services", "Consumer Electronics", "Copper", "Dairy Products", "Data Processing Services", 
  "Dealers-Commercial Vehicles, Tractors, Construction Vehicles", "Depositories, Clearing Houses and Other Intermediaries", 
  "Digital Entertainment", "Distributors", "Diversified", "Diversified Commercial Services", "Diversified consumer products", 
  "Diversified FMCG", "Diversified Metals", "Diversified Retail", "Dredging", "Dyes And Pigments", "E-Learning", 
  "E-Retail/ E-Commerce", "Edible Oil", "Education", "Electrodes & Refractories", "Electronic Media", 
  "Exchange and Data Platform", "Explosives", "Ferro & Silica Manganese", "Fertilizers", 
  "Film Production, Distribution & Exhibition", "Financial Institution", "Financial Products Distributor", 
  "Financial Technology (Fintech)", "Footwear", "Forest Products", "Furniture, Home Furnishing", "Garments & Apparels", 
  "Gas Transmission/Marketing", "Gems, Jewellery And Watches", "General Insurance", "Glass - Consumer", 
  "Glass - Industrial", "Granites & Marbles", "Healthcare Research, Analytics & Technology", "Healthcare Service Provider", 
  "Heavy Electrical Equipment", "Holding Company", "Hospital", "Hotels & Resorts", "Household Appliances", 
  "Household Products", "Houseware", "Housing Finance Company", "Industrial Gases", "Industrial Minerals", 
  "Industrial Products", "Insurance Distributors", "Integrated Power Utilities", "Internet & Catalogue Retail", 
  "Investment Company", "Iron & Steel", "Iron & Steel Products", "IT Enabled Services", "Jute & Jute Products", 
  "Leather And Leather Products", "Leisure Products", "Life Insurance", "Logistics Solution Provider", 
  "LPG/CNG/PNG/LNG Supplier", "Lubricants", "Meat Products including Poultry", "Media & Entertainment", 
  "Medical Equipment & Supplies", "Microfinance Institutions", "Multi Utilities", "Non Banking Financial Company (NBFC)", 
  "Offshore Support Solution Drilling", "Oil Equipment & Services", "Oil Exploration & Production", 
  "Oil Storage & Transportation", "Other Agricultural Products", "Other Bank", "Other Beverages", 
  "Other Capital Market related Services", "Other Construction Materials", "Other Consumer Services", 
  "Other Electrical Equipment", "Other Financial Services", "Other Food Products", "Other Industrial Products", 
  "Other Telecom Services", "Other Textile Products", "Packaged Foods", "Packaging", "Paints", "Paper & Paper Products", 
  "Passenger Cars & Utility Vehicles", "Personal Care", "Pesticides & Agrochemicals", "Petrochemicals", "Pharmaceuticals", 
  "Pharmacy Retail", "Pig Iron", "Plastic Products - Consumer", "Plastic Products - Industrial", 
  "Plywood Boards/ Laminates", "Port & Port services", "Power - Transmission", "Power Distribution", "Power Generation", 
  "Power Trading", "Precious Metals", "Print Media", "Printing & Publication", "Printing Inks", "Private Sector Bank", 
  "Public Sector Bank", "Railway Wagons", "Ratings", "Real Estate Investment Trusts (REITs)", 
  "Real Estate related services", "Refineries & Marketing", "Residential, Commercial Projects", "Restaurants", 
  "Road AssetsToll, Annuity, Hybrid-Annuity", "Road Transport", "Rubber", "Sanitary Ware", "Seafood", 
  "Ship Building & Allied Services", "Shipping", "Software Products", "Speciality Retail", "Specialty Chemicals", 
  "Sponge Iron", "Stationary", "Stockbroking & Allied", "Sugar", "Tea & Coffee", "Telecom - Equipment & Accessories", 
  "Telecom - Cellular & Fixed line services", "Telecom - Infrastructure", "Tour, Travel Related Services", 
  "Tractors", "Trading - Auto components", "Trading - Chemicals", "Trading - Gas", "Trading - Metals", 
  "Trading - Minerals", "Trading - Textile Products", "Trading & Distributors", "Transport Related Services", 
  "TV Broadcasting & Software Production", "Tyres & Rubber Products", "Waste Management", 
  "Water Supply & Management", "Web based media and service", "Wellness", "Zinc"
];